# Site settings
title: "Safril Adi Husada"
email: safriladi@gmail.com
description: "Sebuah Buku Catatan Pemrograman Belaka"
baseurl: ""
url: "https://www.oom.web.id/"
title_description: "Seorang programmer dan web developer yang kadang-kadang menangani C++, Visual Basic, Delphi, SQL, Java, Phyton, HTML, XML, CSS, PHP, Javascript, jQuery, Ruby, ReactJs. Sekarang berstatus sebagai PNS di Mahkamah Agung."
title_image: "https://avatars2.githubusercontent.com/u/43907218?s=460&u=68d4cc6f77cffbbb063b5cdc663ab695d179499f&v=4"
google_analytics: "G-M7B0PTSJV0"
disqus_account: aping
github_repository: https://github.com/apynx/apynx.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: capkatak
github_username:  apynx
instagram_username: apynx
reddit_username: 
linkedin_link: https://www.linkedin.com/in/safriladi/
google_plus_link: 
stackoverflow_link: https://stackoverflow.com/users/14722481/mas-aping
xing_link:
facebook_link: https://www.facebook.com/safril

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://www.oom.web.id\">Oom Blogger</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/apynx/apynx.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown
timezone: "Asia/Jakarta"
permalink: /:year/:month/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [vendor]
